name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: '${{matrix.node}} on ${{matrix.os}}'
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install -g npm@7 # See: <https://github.com/npm/cli/issues/4341#issuecomment-1040608101>
      - run: npm install -g npm
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v1
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - lts/erbium
          - lts/*
